export { default as Table } from './Table'
export { default as TableBody } from './table-body/TableBody'
export { default as TableCaption } from './table-caption/TableCaption'
export { default as TableCell } from './table-cell/TableCell'
export { default as TableFooter } from './table-footer/TableFooter'
export { default as TableHead } from './table-head/TableHead'
export { default as TableHeader } from './table-header/TableHeader'
export { default as TableRow } from './table-row/TableRow'
