import { CheckoutLayout } from '@/components/layouts/checkout-layout'

export const metadata = {
	title: 'Next.js',
	description: 'Generated by Next.js'
}

export default function RootCheckoutLayout({
	children
}: {
	children: React.ReactNode
}) {
	return <CheckoutLayout>{children}</CheckoutLayout>
}
