export { DialogContent } from './dialog-content'
export { DialogDescription } from './dialog-description'
export { DialogFooter } from './dialog-footer'
export { DialogHeader } from './dialog-header'
export * from './dialog-other'
export { DialogOverlay } from './dialog-overlay'
export { DialogTitle } from './dialog-title'
